"""Virtual Machine module"""
import sys

from source.memory.isa import get_regs

instruction_len = 12
exec_log_dump_regs = True
exec_log_dump_data_seg = True
exec_log_dump_stack = True
class VirtualMachine():
    """This class is used to run the bytecode generated by the Assembler"""
    global instruction_len

    def __init__(self, mem, file_name, size):
        """Init method"""
        self.mem = mem
        self.pc = self.mem.pc
        self.byte_code = self.mem.byte_code
        self.running = True
        self.isa = self.mem.isa
        self.regs = self.mem.isa.reg
        self.file = ""
        if ".bin" in file_name:
            self.file = file_name
        
        index = self.file.rfind(".")
        self.log_file = f"{file_name[:index]}_exec.log"

        stack = self.isa.registers
        self.isa.reg[stack["SL"]] = self.mem.offset + 1 #Stack limit register
        self.isa.reg[stack["SB"]] = size
        self.isa.reg[stack["SP"]] = self.isa.reg[stack["SB"]] - 4
        self.isa.reg[stack["FP"]] = 0

        self.read()

    def read(self):
        """Read method, reads the bytecode"""
        if self.pc == 0 and self.file is not None:
            self.byte_code.seek(0)
            self.pc = int.from_bytes(self.byte_code.read(1), 'little')
        while self.running:
            with open(self.log_file, "w") as exec_logs:
                self.byte_code.seek(self.pc)
                line = self.byte_code.read(instruction_len)
                op_code = int.from_bytes(line[0:4], 'little')
                op1 = int.from_bytes(line[4:8], 'little', signed= True)
                op2 = int.from_bytes(line[8:], 'little', signed= True)
                #print(op_code, op1, op2)
                if op_code == 21 and op1 == 99:
                    self.trp99(exec_logs)
                else:
                    if op_code in self.isa.rev_inst:
                        op_code = self.isa.rev_inst[op_code]
                    else:
                        raise Exception(f"Unkown op_codecode {op_code}")

                    if not hasattr(self, op_code):
                        raise Exception(f"Unimplemented op_codecode {op_code}")
                    func = getattr(self, op_code)
                    func(op1, op2)
                    #print(self.regs)
    def TRP(self, typ, _):
        """Executes TRP instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        if typ == 0:
            self.running = False
        elif typ == 1:
            print(self.regs[3], end='', flush=True)
        elif typ == 2:
            byt = sys.stdin.read(1)
            self.regs[3] = int(byt)
        elif typ == 3:
            print(chr(self.regs[3] & 0x000000FF), end='', flush=True)
        elif typ == 4:
            byt = sys.stdin.read(1).encode('ascii')
            self.regs[3] = int.from_bytes(byt, 'little', signed= True)

        else:
            raise Exception(f"Unimplemented trap {typ}")

    def LDB(self, reg, mem_loc):
        """Executes LDB instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        byts = 1
        self.byte_code.seek(mem_loc)
        self.regs[reg] = ord(self.byte_code.read(byts).decode())

    def LDR(self, reg, mem_loc):
        """Executes LDR instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        ints = 4
        self.byte_code.seek(mem_loc)
        self.regs[reg] =  int.from_bytes(self.byte_code.read(ints), 'little', signed= True)

    def LDB1(self, dst, reg):
        """Executes LDB instruction indirec addressing"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        byt = 1
        self.byte_code.seek(self.regs[reg])
        self.regs[dst] = ord(self.byte_code.read(byt).decode())

    def LDR1(self, dst, reg):
        """Executes LDR instruction indirect addressing"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        ints = 4
        self.byte_code.seek(self.regs[reg])
        self.regs[dst] = int.from_bytes(self.byte_code.read(ints), 'little', signed= True)

    def STR(self, src, mem_loc):
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        ints = 4
        self.byte_code.seek(mem_loc)
        byt = int.to_bytes(self.regs[src], ints, 'little', signed= True)
        for i in range(0, ints):
            self.byte_code.write_byte(byt[i])

    def STB(self, src, mem_loc):
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        self.byte_code.seek(mem_loc)
        self.byte_code.write_byte(self.regs[src])

    def STR1(self, src, reg):
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        ints = 4
        self.byte_code.seek(self.regs[reg])
        byt = int.to_bytes(self.regs[src], ints, 'little', signed= True)
        for i in range(0, ints):
            self.byte_code.write_byte(byt[i])

    def STB1(self, src, reg):
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        self.byte_code.seek(self.regs[reg])
        self.byte_code.write_byte(self.regs[src])

    def LDA(self, reg, mem_loc):
        """Executes LDA instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        self.byte_code.seek(0)
        initialPc = int.from_bytes(self.byte_code.read(4), byteorder= 'little', signed= True)
        if mem_loc < initialPc:
            self.regs[reg] =  mem_loc
        else:
            print(f"Label not associated with directive, location: {mem_loc}")

    def MOV(self, dst, src):
        """Executes MOV instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        self.regs[dst] = self.regs[src]

    def MOVI(self, dst,  imm):
        """Executes MOV instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        self.regs[dst] = imm

    def ADD(self, dst, src):
        """Executes ADD instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        self.regs[dst] = self.regs[dst] + self.regs[src]

    def ADI(self, dst, imm):
        """Executes ADI instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        self.regs[dst] = self.regs[dst] + imm

    def MUL(self, dst, src):
        """Executes MUL instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        self.regs[dst] = self.regs[dst] * self.regs[src]

    def MULI(self, dst, imm):
        """Executes MULI instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        self.regs[dst] = self.regs[dst] * imm

    def DIV(self, dst, src):
        """Executes DIV instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        self.regs[dst] =  self.regs[dst] // self.regs[src]
        self.regs[dst] = int(self.regs[dst])

    def DIVI(self, dst, imm):
        """Executes DIV instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        self.regs[dst] =  self.regs[dst] // imm
        self.regs[dst] = int(self.regs[dst])

    def SUB(self, dst, src):
        """Executes SUB instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        self.regs[dst] = self.regs[dst] - self.regs[src]

    def CMP(self, dst, src):
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        if self.regs[dst] == self.regs[src]:
            self.regs[dst] = 0
        elif self.regs[dst] > self.regs[src]:
            self.regs[dst] = 1
        elif self.regs[dst] < self.regs[src]:
            self.regs[dst] = -1

    def CMPI(self, dst, imm):
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc
        if self.regs[dst] == imm:
            self.regs[dst] = 0
        elif self.regs[dst] > imm:
            self.regs[dst] = 1
        elif self.regs[dst] < imm:
            self.regs[dst] = -1

    def JMP(self, mem_loc, _):
        """Goes to the specified memory location"""
        self.pc = mem_loc
        self.regs[16] = self.pc

    def JMR(self, reg, _):
        """Goes to the specified memory location"""
        self.pc = self.regs[reg]
        self.regs[16] = self.pc

    def BRZ(self, reg, mem_loc):
        """Goes to the specified memory location"""
        if self.regs[reg] == 0:
            self.pc = mem_loc
            self.regs[16] = self.pc
        else:
            self.pc = self.pc + instruction_len
            self.regs[16] = self.pc

    def BNZ(self, reg, mem_loc):
        """Goes to the specified memory location"""
        if self.regs[reg] != 0:
            self.pc = mem_loc
            self.regs[16] = self.pc
        else:
            self.pc = self.pc + instruction_len
            self.regs[16] = self.pc

    def BGT(self, reg, mem_loc):
        """Goes to the specified memory location"""
        if self.regs[reg] > 0:
            self.pc = mem_loc
            self.regs[16] = self.pc
        else:
            self.pc = self.pc + instruction_len
            self.regs[16] = self.pc

    def BLT(self, reg, mem_loc):
        """Goes to the specified memory location"""
        if self.regs[reg] < 0:
            self.pc = mem_loc
            self.regs[16] = self.pc
        else:
            self.pc = self.pc + instruction_len
            self.regs[16] = self.pc

    def AND(self, dst, src):
        """Executes AND instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc

        if self.regs[dst] != 0:
            self.regs[dst] = 1
        else:
            self.regs[dst] = 0

        if self.regs[src] != 0:
            self.regs[src] = 1
        else:
            self.regs[src] = 0

        self.regs[dst] = self.regs[dst] and self.regs[src]

    def OR(self, dst, src):
        """Executes OR instruction"""
        self.pc = self.pc + instruction_len
        self.regs[16] = self.pc

        if self.regs[dst] != 0:
            self.regs[dst] = 1
        else:
            self.regs[dst] = 0

        if self.regs[src] != 0:
            self.regs[src] = 1
        else:
            self.regs[src] = 0

        self.regs[dst] = self.regs[dst] or self.regs[src]

    def trp99(self, exec_logs):
        if exec_log_dump_regs or exec_log_dump_data_seg or exec_log_dump_stack:
            print("")
            exec_logs.write("\n")
        registers = self.mem.isa.registers
        
        if exec_log_dump_regs:
            for reg_name in registers.keys():
                reg_index = registers[reg_name]
                reg_status = f"{reg_name} = {self.regs[reg_index]}"
                print(reg_status)
                exec_logs.write(f"{reg_status}\n")
            print("")
            exec_logs.write("\n")
        
        if exec_log_dump_stack:
            # +4 since pointing to next unused location
            sp_curr = self.regs[19] + 4
            # -4 since point to last int in stack, not where bytes end
            sp_last = self.regs[18]  - 4
            while sp_curr <= sp_last:
                sp_curr_bytes = sp_curr.to_bytes(4, byteorder="little", signed=True)
                value_bytes = self.byte_code.read(sp_curr)
                print(value_bytes)
                value = int.from_bytes(value_bytes, 'little', signed=True)
                stack_status = f"0x{sp_curr_bytes.hex()} ({sp_curr}) = 0x{value_bytes.hex()} ({value})"
                print(stack_status)
                exec_logs.write(f"{stack_status}\n")
                sp_curr += 4



